### ISSUE TITLE
Group children

### ISSUE THREAD

**Issue by henriavelabarbe** [leboncoin/simple-ansible-inventory#1]
Hi,
thanks for sharing this script, I love the idea to define the inventory by host.
Could you tell me if one can define group children using it ?

Regards,
Henri Chapelle

**Comment by bbayszczak** [comment]
Hi,
You mean defining a child group of another group ?

Regards,
Benoit

**Comment by henriavelabarbe** [comment]
Yes, that's right.
We would like to have a group (non dynamic) linux with subgroup centos, redhat, debian...
I don't see how to do it using simple ansible inventory.

Regards,
Henri

**Comment by bbayszczak** [comment]
You cannot
The idea was to keep it simple and avoid any group inclusion.
What you can do for example is assigning groups `linux` and `debian` to your host

**Comment by bbayszczak** [comment]
I wanted to avoid the following:
> Host a is defined with group A
> But group A is a member of group B
> So the host is also member of group B

The fact that the host will also be a member of group B wouldn't be easily readable by reading host definition in file

**Comment by henriavelabarbe** [comment]
Ok, I'll do with additional groups, thanks !

**Comment by bbayszczak** [comment]
You're welcome !
