### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by kmonticolo** [leboncoin/simple-ansible-inventory#2]
python script throws me the following error:

./simple-ansible-inventory.py:241: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  raw_confs_list.append(yaml.load(fd))

**Comment by bbayszczak** [comment]
It was because of a deprecation of `yaml.load` in `pyyaml>=5.1`
I replaced `yaml.load` by `yaml.safe_load` in https://github.com/leboncoin/simple-ansible-inventory/commit/14badff930cf0915591e391acb459f89728361ce

It will work now

**Comment by kmonticolo** [comment]
cool!, thanks.
